#!/bin/bash

# daemons
polybar benq -r &
polybar acer -r &
sxhkd &

# monitor stuff
xrandr --output DVI-D-0 --auto --primary
xrandr --output HDMI-0 --auto --right-of DVI-D-0

# bspwm config
bspc monitor DVI-D-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9

bspc config border_width		2
bspc config normal_border_color		"#272727"
bspc config focused_border_color	"#d79921"
bspc config window_gap			15
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer	true

bspc config single_monocle true
bspc config borderless_monocle   true
bspc config gapless_monocle	 true

#
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape
