#!/bin/bash

dots=~/Documents/Repos/dotfiles

cp ~/.config/bspwm/bspwmrc $dots
cp ~/.config/sxhkd/sxhkdrc $dots
cp ~/.config/polybar/config $dots/polybar
cp ~/.vimrc $dots
cp ~/.zshrc $dots
cp ~/.tmux.conf $dots

cd $dots && git diff

if [[ "$#" -gt 0 ]]; then
	if [[ "$1" -eq push ]]; then
		git add -A
		if [[ -z "$2" ]]; then
			git commit -m "+"
		else
			git commit -m $2
		fi
		git push
	fi
fi
