#!/bin/bash
# automatically sync config files with git
# automatic commit msg is first line added or first line deleted if no additions were made

dots=~/Dev/Repos/dotfiles
scripts=~/.local/bin

if [ $# -eq 0 ]
then
	echo "no flags supplied"
	echo "available flags:"
	echo "-s 			sync dotfiles with local dotfiles git repo"
	echo "-p COMMIT_MSG 		push changes to remote git repo"
	echo "                      if COMMIT_MSG is empty, automatically generate commit msg"
else
	cd ${dots}
fi

while [ $# -gt 0 ]
do
	case "$1" in
		-s|--sync)
			mkdir -p -v ${dots}/polybar ${dots}/scripts
			cp ~/.config/bspwm/bspwmrc ${dots}
			cp ~/.config/sxhkd/sxhkdrc ${dots}
			cp ~/.config/polybar/* ${dots}/polybar
			cp ~/.vimrc ${dots}
			cp ~/.zshrc ${dots}
			cp ~/.tmux.conf ${dots}
			cp ${scripts}/* ${dots}/scripts
            changes=$(git diff --compact-summary)
            if [ -z "${changes}" ]
            then
                echo "no changes to dotfiles"
            else
                echo "${changes}"
            fi
			shift
			;;
		-p|--push)
			git add -A
			if [ $# -eq 1 ]
			then
                msg=$(git diff --cached | grep '^[+][^+]' | head -n 1 | xargs)
                [ -z "${msg}" ] && msg=$(git diff --cached | grep '^[-][^-]' | head -n 1 | xargs)
				git commit -m "${msg}" && echo "automatic commit msg=\"${msg}\"" && git push
			else
				git commit -m "$2" && git push
			fi
			shift
			;;
		*)
			break
			;;
	esac
done
