#!/bin/bash

dots=~/Documents/Repos/dotfiles
scripts=/usr/local/bin

if [ $# -eq 0 ]
then
	echo "no flags supplied"
	echo "available flags:"
	echo "-s 			sync dotfiles with local dotfiles git repo"
	echo "-p COMMIT_MSG 		push changes to remote git repo, optional msg"
else
	cd $dots
fi

while [ $# -gt 0 ]
do
	case "$1" in
		-s|--sync)
			cp ~/.config/bspwm/bspwmrc $dots
			cp ~/.config/sxhkd/sxhkdrc $dots
			cp ~/.config/polybar/* $dots/polybar
			cp ~/.vimrc $dots
			cp ~/.zshrc $dots
			cp ~/.tmux.conf $dots
			cp $scripts/* $dots/scripts
			git diff --compact-summary
			shift
			;;
		-p|--push)
			git add -A
			if [ $# -eq 1 ]
			then
				msg=update
				git commit -m "$msg" && echo "automatic commit msg=\"$msg\"" && git push
			else
				git commit -m "$2" && git push
			fi
			shift
			;;
		*)
			break
			;;
	esac
done
