#!/bin/bash


statefile=~/.night_state.txt
[ ! -f "$statefile" ] && echo day > $statefile
state=$(<$statefile)
if [ $# -gt 0 ]
then
	case "$1" in
		label)
			echo $state
			;;
		icon)
			if [ $state = night ]
			then
				echo -ne "\uF186"  # moon
			fi
			if [ $state = day ]
			then
				echo -ne "\uF185"  # sun
			fi
			;;
		toggle)
			if [ $state = night ]
			then
				redshift -x
				echo day > $statefile
			fi
			if [ $state = day ]
			then
				redshift -O 1900 -P
				echo night > $statefile
			fi
			;;
	esac
fi
