#!/bin/bash
inside_git_repo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"

if [ "$inside_git_repo" ]; then
    echo "#(basename `git rev-parse --show-toplevel`)"
else
    echo "no git repo"
fi
